<?php

namespace Mesh\EdmMailChimpBundle\Repository;

use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\Query;

use Mesh\EncompassBundle\Behaviour\SearchableRepositoryBehavior;
use Mesh\EncompassBundle\Entity\Site;
use Mesh\EdmMailChimpBundle\Entity\EdmSyncUserQueue;

/**
 * EdmSyncUserQueueRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EdmSyncUserQueueRepository extends EntityRepository
{
    use SearchableRepositoryBehavior;

    public function getWaitingForSite(Site $site, $limit = 10)
    {
        $qb = $this->createQueryBuilder('q')
            ->where('q.site = :site')
            ->andWhere('q.status = :status')
            ->orderBy('q.created_at', 'ASC')
            ->setMaxResults($limit);

        $qb->setParameter(':site', $site);
        $qb->setParameter(':status', EdmSyncUserQueue::STATUS_WAITING);

        return $qb->getQuery()->getResult();
    }
}
